[package]
name = "tantivy-ik"
version = "0.1.0"
authors = ["blueshen <zhiyi.shen@gmail.com>"]
license = "LGPL-2.1-only"
categories = ["database-implementations", "data-structures"]
description = """chinese segment, ik-rs for tantivy"""
documentation = "https://docs.rs/tantivy-ik"
homepage = "https://github.com/blueshen/tantivy-ik"
repository = "https://github.com/blueshen/tantivy-ik"
readme = "README.md"
keywords = ["search", "information", "retrieval", "tantivy", "ik-analyzer"]
edition = "2021"

[dependencies]
tantivy = "0.19.0"
ik-rs = "0.2.0"
once_cell = "1.16.0"